name: Render Quarto PDF
on:
  push:
  schedule:
    - cron: '0 5 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_VERSION: '4.3.2'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y libicu70 libcurl4-openssl-dev r-base

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}
          use-public-rspm: true

      - name: Query R package dependencies
        run: |
          install.packages(c('remotes', 'here'))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ env.R_VERSION }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ env.R_VERSION }}-1-

      - name: Install R dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages("pkgdown")
        shell: Rscript {0}

      - name: Install TinyTeX
        run: |
          wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
          echo "PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH" >> $GITHUB_ENV

      - name: Install LaTeX Packages with TinyTeX
        run: |
          tlmgr install marvosym parskip fancyhdr lastpage xecjk hyperref xcolor

      - name: Render PDF
        run: |
          quarto render cv-jph.qmd --to pdf

      - name: Set up Git Config
        run: |
          git config --global user.name 'John Paul Helveston'
          git config --global user.email 'john.helveston@gmail.com'

      - name: Commit and Push PDF
        run: |
          git add cv-jph.pdf
          git commit -m "Update rendered PDF"
          git push