name: Render Quarto PDF

on:
  push:
  schedule:
    # Scheduled to run at midnight every Sunday
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install R Packages
      run: |
        install.packages(c('pander', 'stringr', 'dplyr', 'googlesheets4', 'lubridate', 'kableExtra', 'xml2', 'rvest'))

    - name: Install LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        packages: |
          latexmk
          marvosym
          parskip
          fancyhdr
          lastpage
          xeCJK
          hyperref
          color

    - name: Install Quarto
      run: |
        wget -qO- "https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.149/quarto-1.1.149-linux-amd64.deb" | sudo dpkg -i -

    - name: Render PDF
      run: |
        quarto render cv-jph.qmd --to pdf

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: rendered-pdf
        path: cv-jph.pdf
